# render.yaml

services:

  - type: web
    name: Men-style-shop

    rootDir: server

    env: node

    buildCommand: npm install
  
    startCommand: node server.js

    plan: free

    envVars:
      - key: PORT
        value: 5000 
